owner: netbox-community
repo: netbox-chart
remote: origin
target-branch: develop
sign: true
key: NetBox Community
chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
generate-release-notes: true
